### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by nardbyte** [eforce67/BrawlStars-ComputerVision#1]
![Screenshot 2024-05-26 133942](https://github.com/eforce67/BrawlStars-ComputerVision/assets/22382010/ba09e7ab-01c4-4bfa-a7c1-608c49f18fdd)

Hello, i have that problem maybe i dont see best.pickle
can please help me for config this one :)

**Comment by eforce67** [comment]
best.pickle is given intentionally when the overall training is done. You can set the configuration to have a more limited population and limit the number-of-runs in the config.
